# Generated by Django 2.0.3 on 2018-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('corp_name', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('atm', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('fries', models.BooleanField(default=False)),
                ('medicine', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('bakery', models.BooleanField(default=False)),
                ('lotto', models.BooleanField(default=False)),
                ('sportstoto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
