# Generated by Django 2.0.3 on 2018-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvs',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
